version: '3.2'
services:

    fcd-producer:
        image: lgslm/fcd-kafka-clients:v1.0.0
        hostname: fcd-producer
        restart: unless-stopped
        environment:
            - ZOOKEEPER_SERVERS=zookeeper:2181 
            - KAFKA_CLIENT_TYPE=producer
            - TOPIC=taxi
        networks:
          - kafka-clients-net

    fcd-consumer:
        image: lgslm/fcd-kafka-clients:v1.0.0
        hostname: fcd-consumer
        restart: unless-stopped
        environment:
            - ZOOKEEPER_SERVERS=zookeeper:2181
            - KAFKA_CLIENT_TYPE=consumer-elasticsearch
            - TOPIC=taxi
        depends_on:
            - fcd-producer
        expose:
            - "9092"
        networks:
          - kafka-clients-net

networks:
        kafka-clients-net:
            external: true
