version: '3.2'
services:
    zoo1:
        image: lgslm/zookeeper:v1.0.0
        hostname: zoo1
        environment:
            - MYID=1
        expose:
            - "2181"
        ports:
            - "2181:2181"
        networks:
          - kafka-clients-net
    
    kafka1:
        image: lgslm/kafka:v1.0.0
        hostname: kafka1
        environment:
            - SERVICE_PRECONDITION=zoo1:2181
            - ZOOKEEPER_SERVERS=zoo1:2181
            - TOPIC=taxi
        depends_on:
            - zoo1
        expose:
            - "9092"
        networks:
          - kafka-clients-net
    
    es01:
        image: lgslm/elasticsearch:v1.0.0
        hostname: es01
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
          - kafka-clients-net
    
    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.1
        environment:
          ELASTICSEARCH_HOSTS: http://es01:9200
        depends_on:
          - es01
        ports:
          - "5601:5601"
        networks:
          - kafka-clients-net 

networks:
        kafka-clients-net:
            external: true
